### ISSUE TITLE
Got Error Update PlayStore

### ISSUE THREAD

**Issue by cakgooder** [hyugogirubato/pymangaplus#2]
Got an error like this when running example usage code
`pymangaplus.utils.NEWVERSIONAVAILABLE: Please update the latest version from the store to continue using the app.(10300)`

**Comment by hyugogirubato** [comment]
I have to update the rest because the API needs to evolve, I will make the change this weekend. Thanks for reporting @cakgooder

**Comment by hyugogirubato** [comment]
@cakgooder 
The problem has just been corrected with the new version. You can now use their API again and this time based on the original protobuf.
